# -*- coding: utf-8 -*-
"""stateanalysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17LVvUcMvFlcfVEy-RUyYik9gLqQVoipc
"""

from google.colab import files

uploaded = files.upload()

!pip install prophet plotly gradio

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from prophet import Prophet


FILES = [
    "api_data_aadhar_enrolment_0_500000.csv",
    "api_data_aadhar_enrolment_500000_1000000.csv",
    "api_data_aadhar_enrolment_1000000_1006029.csv"
]

df = pd.concat([pd.read_csv(f) for f in FILES], ignore_index=True)

df["date"] = pd.to_datetime(df["date"], format="%d-%m-%Y", errors="coerce")
df = df.dropna(subset=["date"])

df["total_enrolments"] = (
    df["age_0_5"] + df["age_5_17"] + df["age_18_greater"]
)

df["year_month"] = df["date"].dt.to_period("M").astype(str)


state_total = (
    df.groupby("state")["total_enrolments"]
    .sum()
    .reset_index()
    .sort_values("total_enrolments", ascending=False)
)

fig_top_states = px.bar(
    state_total.head(10),
    x="total_enrolments",
    y="state",
    orientation="h",
    title="Top 10 States by Total Aadhaar Enrolments",
    labels={"total_enrolments": "Total Enrolments", "state": "State"}
)

fig_top_states.update_layout(yaxis=dict(autorange="reversed"))
fig_top_states.show()



state_month = (
    df.groupby(["state", "year_month"])["total_enrolments"]
    .sum()
    .reset_index()
)

top_states = state_total.head(6)["state"].tolist()

fig_state_behavior = px.line(
    state_month[state_month["state"].isin(top_states)],
    x="year_month",
    y="total_enrolments",
    color="state",
    title="Monthly Aadhaar Enrolment Behavior Across Major States",
    labels={
        "year_month": "Month",
        "total_enrolments": "Total Enrolments",
        "state": "State"
    }
)

fig_state_behavior.show()



def prophet_state_forecast(state_name, months=6):
    state_df = df[df["state"] == state_name]

    monthly = (
        state_df.groupby("year_month")["total_enrolments"]
        .sum()
        .reset_index()
    )

    prophet_df = pd.DataFrame({
        "ds": pd.to_datetime(monthly["year_month"]),
        "y": monthly["total_enrolments"]
    })

    model = Prophet(yearly_seasonality=True)
    model.fit(prophet_df)

    future = model.make_future_dataframe(periods=months, freq="M")
    forecast = model.predict(future)

    fig = go.Figure()

    fig.add_trace(go.Scatter(
        x=prophet_df["ds"],
        y=prophet_df["y"],
        mode="lines",
        name="Actual"
    ))

    fig.add_trace(go.Scatter(
        x=forecast["ds"],
        y=forecast["yhat"],
        mode="lines",
        line=dict(dash="dash"),
        name="Forecast"
    ))

    fig.add_trace(go.Scatter(
        x=forecast["ds"],
        y=forecast["yhat_upper"],
        mode="lines",
        line=dict(width=0),
        showlegend=False
    ))

    fig.add_trace(go.Scatter(
        x=forecast["ds"],
        y=forecast["yhat_lower"],
        mode="lines",
        fill="tonexty",
        name="Confidence Interval"
    ))

    fig.update_layout(
        title=f"Aadhaar Enrolment Forecast – {state_name}",
        xaxis_title="Date",
        yaxis_title="Total Enrolments"
    )

    fig.show()



for state in top_states[:4]:
    prophet_state_forecast(state)

import pandas as pd
import plotly.express as px


FILES = [
    "api_data_aadhar_enrolment_0_500000.csv",
    "api_data_aadhar_enrolment_500000_1000000.csv",
    "api_data_aadhar_enrolment_1000000_1006029.csv"
]

df = pd.concat([pd.read_csv(f) for f in FILES], ignore_index=True)

df["date"] = pd.to_datetime(df["date"], format="%d-%m-%Y", errors="coerce")
df = df.dropna(subset=["date"])

df["total_enrolments"] = (
    df["age_0_5"] + df["age_5_17"] + df["age_18_greater"]
)



district_total = (
    df.groupby(["state", "district"])["total_enrolments"]
    .sum()
    .reset_index()
    .sort_values("total_enrolments", ascending=False)
)

fig_top_districts = px.bar(
    district_total.head(15),
    x="total_enrolments",
    y="district",
    color="state",
    orientation="h",
    title="Top 15 Districts by Total Aadhaar Enrolments",
    labels={
        "total_enrolments": "Total Enrolments",
        "district": "District",
        "state": "State"
    }
)

fig_top_districts.update_layout(yaxis=dict(autorange="reversed"))
fig_top_districts.show()


fig_bottom_districts = px.bar(
    district_total.tail(15),
    x="total_enrolments",
    y="district",
    color="state",
    orientation="h",
    title="Bottom 15 Districts (Lagging Aadhaar Enrolment)",
    labels={
        "total_enrolments": "Total Enrolments",
        "district": "District",
        "state": "State"
    }
)

fig_bottom_districts.update_layout(yaxis=dict(autorange="reversed"))
fig_bottom_districts.show()



low_districts = district_total.tail(50)

fig_geo_pattern = px.box(
    low_districts,
    x="state",
    y="total_enrolments",
    title="Distribution of Low-Enrolment Districts Across States",
    labels={
        "total_enrolments": "District Enrolments",
        "state": "State"
    }
)

fig_geo_pattern.show()



fig_heatmap = px.density_heatmap(
    district_total,
    x="state",
    y="district",
    z="total_enrolments",
    color_continuous_scale="Viridis",
    title="District-Level Aadhaar Enrolment Intensity Heatmap"
)

fig_heatmap.show()